### ISSUE TITLE
Add LO feature to "break down" objectives into sub-objectives

### ISSUE THREAD

**Issue by darrensiegel** [Simon-Initiative/oli-torus#632]
This task involves refactoring the LO page to enforce a 2 tier hierarchy of objectives and skills, while also enforcing that only skills can be attached to activities.

**Requirements:**
- Torus will continue to support a separate “Learning Objectives” area in the UI which will allow the creation and iteration of the course learning model. This will initially include a 2-tier level of learning objectives and skills, but remain flexible enough that this can be changed later if necessary
- The data model and user interface will enforce that only “leaf” nodes in the hierarchy (skills) can be attached to activities.
- Torus will support a guided approach if reattaching skills to activities when a user “breaks down” a current skill into an objective will lower level skill parts
- Torus will provide a way in the learning objectives view to see where in the course hierarchy that LOs are being used (by looking at where they are attached, then rolling that up through the curriculum hierarchy)

**Tasks:**
- [x] ~Refactor Learning Objectives view to use new 2-tier structure~
- [x] ~Add migration for existing hierarchical objectives to new 2-tier model~
- [x] Investigate adding the ability to "break down" a skill into a learning objective with children skills, while guiding the user through reattaching new skills to the activities that used the old skill
- [ ] Add view of objectives through the curriculum hierarchy lens
- [ ] Enforce (or highly encourage) attachment of learning objective to every activity
- [ ] Ensure new parent objective title is not blank
- [ ] Investigate building out Objectives Service API
- [ ] Upgrade Typeahead component and rebuild ObjectivesSelection
- [ ] Ensure at least one objective is selected when creating an activity
- [ ] Only allow leaf objectives to be attached
- [ ] Cancel activity creation on modal cancel or exit
- [ ] Dynamic objective examples
- [ ] Remove objectives caching in Editor state or move to redux https://react-redux.js.org/api/hooks#useselector
- [ ] Investigate objectives bulk-import (paste in, newline separated)

**Comment by LEDThereBeLight** [comment]
Closing as done.
