### ISSUE TITLE
Dynamic Questions: CMU-170

### ISSUE THREAD

**Issue by darrensiegel** [Simon-Initiative/oli-torus#740]
Template activity support (dynamic questions)

- [x] Allow existing authoring-eval to be used from Torus, in a batch manner
- [x] Build a Torus transformation that invokes the lambda function, and performs variable substitution within the original activity model
- [ ] Introduce variable authoring support into all activity types.  Consider porting existing Echo impl. 
- [x] Enable the Echo eval engine to serve both Tokamak and Proton
