### ISSUE TITLE
Support Legacy OLI semantic elements: CMU-166

### ISSUE THREAD

**Issue by darrensiegel** [Simon-Initiative/oli-torus#889]
The following higher level semantic elements are yet to have an equivalent in Torus:

- [x] `theorem` (https://eliterate.atlassian.net/browse/MER-1415)
- [x] `figure` (https://eliterate.atlassian.net/browse/MER-1414)
- [x] `definition` (https://eliterate.atlassian.net/browse/MER-1413)
- [x] `dialog` (https://eliterate.atlassian.net/browse/MER-1416)
- [x] `conjugation` (https://eliterate.atlassian.net/browse/MER-1417)

Additional ticket to handle the visibility of the options: https://eliterate.atlassian.net/browse/MER-1418
