### ISSUE TITLE
Add bibliography and citation support: CMU-164

### ISSUE THREAD

**Issue by darrensiegel** [Simon-Initiative/oli-torus#891]
The OLI workbook page DTD allows for bibliography references to be included by way of an XML implementation of BibTex (http://bibtexml.sourceforge.net, and http://www.bibtex.org/). Torus will need to provide a level of backwards compatibility, at least during ingesetion.  But we have an opportunity to assess whether BibTex as a model meets current and future needs. 

Consider perhaps a simplified workflow for authors where a dedicated view within a project exists for adding bibliography entries, as opposed to how this is handled in Echo where each page requires the specification of a reference. 

Work to be completed for 5/12/22:
- [x] Form-driven authoring interface
- [x] Add ability to create "citation" inline references to existing bibliography entries
- [x] Build client-side entry rendering support for delivery

Work to be completed for 5/26/22:
- [ ] Course-digest work to migrate pages with entries
- [ ] Torus ingest work to ingest bib entries
